import datetime
import subprocess
import joanne

list_of_vars = [
    "sounding",
    "launch_time",
    "alt",
    "lat",
    "lon",
    "p",
    "ta",
    "rh",
    "wspd",
    "wdir",
    "u",
    "v",
    "theta",
    "q",
    "PW",
    # "static_stability",
    "low_height_flag",
    # "cloud_flag",
    "platform",
    "flight_height",
    "flight_lat",
    "flight_lon",
    "sonde_id",
    "N_ptu",
    "N_gps"
]

nc_attrs = {
    "sounding": {
        "standard_name": "sounding",
        "long_name": "Sonde number",
        "units": "",
        "axis": "T",
    },
    "sonde_id": {
        "description": "unique sonde ID in the format PLATFORM_FLIGHT-ID_sSONDE-NUMBER-FOR-THE-FLIGHT",
        "long_name": "sonde identifier",
        "cf_role": "trajectory_id",
    },
    "launch_time": {
        "standard_name": "time",
        "long_name": "Time of dropsonde launch",
        "units": "seconds since 1970-01-01 00:00:00 UTC",
        "calendar": "gregorian",
        "axis": "T",
    },
    "alt": {
        "standard_name": "geopotential_height",
        "long_name": "Geopotential Height",
        "description": "Height obtained by integrating upwards the atmospheric thickness estimated from the hypsometric equation",
        "units": "m",
        "axis": "Z",
        "positive": "up",
    },
    "lat": {
        "standard_name": "latitude",
        "long_name": "Latitude",
        "units": "degrees_north",
        "axis": "X",
    },
    "lon": {
        "standard_name": "longitude",
        "long_name": "Longitude",
        "units": "degrees_east",
        "axis": "Y",
    },
    "p": {
        "standard_name": "air_pressure",
        "long_name": "Atmospheric Pressure",
        "units": "Pa",
        "coordinates": "launch_time lon lat alt",
    },
    "ta": {
        "standard_name": "air_temperature",
        "long_name": "Dry Bulb Temperature",
        "units": "K",
        "coordinates": "launch_time lon lat alt",
    },
    "theta": {
        "standard_name": "potential_temperature",
        "long_name": "Potential Temperature",
        "units": "K",
        "coordinates": "launch_time lon lat alt",
    },
    "rh": {
        "standard_name": "relative_humidity",
        "long_name": "Relative Humidity",
        "units": "",
        "coordinates": "launch_time lon lat alt",
    },
    "q": {
        "standard_name": "specific_humidity",
        "long_name": "Specific humidity",
        "units": "kg kg-1",
        "coordinates": "launch_time lon lat alt",
    },
    "wspd": {
        "standard_name": "wind_speed",
        "long_name": "Wind Speed",
        "units": "m s-1",
        "coordinates": "launch_time lon lat alt",
    },
    "u": {
        "standard_name": "eastward_wind",
        "long_name": "u-component of the wind",
        "units": "m s-1",
        "coordinates": "launch_time lon lat alt",
    },
    "v": {
        "standard_name": "northward_wind",
        "long_name": "v-component of the wind",
        "units": "m s-1",
        "coordinates": "launch_time lon lat alt",
    },
    "wdir": {
        "standard_name": "wind_from_direction",
        "long_name": "Wind Direction",
        "units": "degrees",
        "coordinates": "launch_time lon lat alt",
    },
    "PW": {
        "standard_name": "precipitable_water",
        "long_name": "integrated water vapour in the measured column",
        "units": "kg m-2",
        "coordinates": "launch_time",
    },
    "static_stability": {
        "standard_name": "static_stability",
        "long_name": "static stability",
        "description": "gradient of potential temperature along the pressure grid",
        "units": "K hPa-1",
        "coordinates": "launch_time lon lat alt",
    },
    "low_height_flag": {
        "long_name": "flag to indicate if flight height at launch was low",
        "flag_values": "1, 0",
        "flag_meanings": "flight height below 4 km flight height at or above 4 km",
        "units": "",
        "valid_range": "0, 1",
    },
    "cloud_flag": {
        "long_name": "flag to indicate presence of cloud",
        "flag_values": "1, 0",
        "flag_meanings": "cloud no_cloud",
        "units": "",
        "valid_range": "0, 1",
    },
    "platform": {
        "standard_name": "platform",
        "long_name": "platform from which the sounding was made",
        "units": "",
        "coordinates": "launch_time",
    },
    "flight_height": {
        "standard_name": "height",
        "long_name": "height of the aircraft when the dropsonde was launched",
        "units": "m",
        "coordinates": "launch_time",
    },
    "flight_lat": {
        "standard_name": "latitude",
        "long_name": "north latitude of the aircraft when the dropsonde was launched",
        "units": "degrees_north",
        "coordinates": "launch_time",
    },
    "flight_lon": {
        "standard_name": "longitude",
        "long_name": "east longitude of the aircraft when the dropsonde was launched",
        "units": "degrees_east",
        "coordinates": "launch_time",
    },
    "N_ptu": {
        "description": "number of observations used to derive level 3 PTU-data",
        "units": "",
        "coordinates": "launch_time lon lat alt",
        "standard_name": "number_of_observations",
    },
    "N_gps": {
        "description": "number of observations used to derive level 3 GPS-data",
        "units": "",
        "coordinates": "launch_time lon lat alt",
        "standard_name": "number_of_observations",
    },
}

nc_dims = {
    "sounding": ["sounding"],
    "sonde_id": ["sounding"],
    "launch_time": ["sounding"],
    "alt": ["alt"],
    "lat": ["sounding", "alt"],
    "lon": ["sounding", "alt"],
    "p": ["sounding", "alt"],
    "ta": ["sounding", "alt"],
    "rh": ["sounding", "alt"],
    "wspd": ["sounding", "alt"],
    "wdir": ["sounding", "alt"],
    "u": ["sounding", "alt"],
    "v": ["sounding", "alt"],
    "theta": ["sounding", "alt"],
    "q": ["sounding", "alt"],
    "PW": ["sounding"],
    "static_stability": ["sounding", "alt"],
    "low_height_flag": ["sounding"],
    "cloud_flag": ["sounding", "alt"],
    "platform": ["sounding"],
    "flight_height": ["sounding"],
    "flight_lat": ["sounding"],
    "flight_lon": ["sounding"],
    "N_ptu": ["sounding", "alt"],
    "N_gps": ["sounding", "alt"],
}

nc_global_attrs = {
    "title": "EUREC4A JOANNE Level-3",
    "Conventions": "CF-1.8",
    "campaign_id": "EUREC4A",
    "project_id": "JOANNE",
    "instrument_id": "Vaisala RD-41",
    "product_id": "Level-3",
    "AVAPS-Software-version": "Version 4.1.2",
    "ASPEN-version": "BatchAspen v3.4.3",
    "JOANNE-version": joanne.__version__,
    "author": "Geet George",
    "author_email": "geet.george@mpimet.mpg.de",
    "featureType": "trajectory",
    "creation_time": str(datetime.datetime.utcnow()) + " UTC",
}
